Polishes compiler test messages

diff --git a/compiler/test/.should_accept.bats.template b/compiler/test/.should_accept.bats.template
--- a/compiler/test/.should_accept.bats.template
+++ b/compiler/test/.should_accept.bats.template
@@ -14,14 +14,17 @@ testName=${testName#.} # optional dot prefix for hiding the .bats file
 
 @test "compiler $testName" {
     cd "$BATS_TEST_DIRNAME/$testName"
-    deepdive compile ||
-    DEEPDIVE_COMPILE_INPUT_JSON= deepdive compile
+    deepdive compile || {
+        [[ -e "$DEEPDIVE_COMPILE_INPUT_JSON" ]] &&
+        echo '# Retrying without cached $DEEPDIVE_COMPILE_INPUT_JSON' &&
+        DEEPDIVE_COMPILE_INPUT_JSON= deepdive compile
+    }
     if [[ -x validate-compiled-config ]]; then
-        echo "Validating run/compiled/config.json"
+        echo "# Validating run/compiled/config.json"
         ./validate-compiled-config -r run/compiled/config.json
     fi
     if [[ -x validate-compiled-code ]]; then
-        echo "Validating run/compiled/code-*.json"
+        echo "# Validating run/compiled/code-*.json"
         ./validate-compiled-code -r run/compiled/code-*.json
     fi
 }
