Migrates tests for extractors and calibration
from SettingsParserSpec.scala

diff --git a/compiler/test/.should_reject.bats.template b/compiler/test/.should_reject.bats.template
--- a/compiler/test/.should_reject.bats.template
+++ b/compiler/test/.should_reject.bats.template
@@ -14,5 +14,10 @@ testName=${testName#.} # optional dot prefix for hiding the .bats file
 
 @test "compiler $testName" {
     cd "$BATS_TEST_DIRNAME/$testName"
-    ! deepdive compile
+    if ! deepdive compile; then
+        echo "deepdive-compile rejected the app with error"
+        # TODO check specific error message as well
+    else
+        echo "deepdive-compile did not return error"; false
+    fi
 }
