Tries to load weights automatically if not done

diff --git a/inference/deepdive-model b/inference/deepdive-model
--- a/inference/deepdive-model
+++ b/inference/deepdive-model
@@ -74,16 +74,24 @@ case $Command in
                         rsync -avH --delete --copy-unsafe-links run/model/factorgraph{,.done} "$dest"/
                         ;;
                     weights)
+                        # automatically load weights only if learning is already done
+                        if ! deepdive-"done" data/model/weights &&
+                             deepdive-"done" process/model/learning; then
+                            DEEPDIVE_PLAN_EDIT=false \
+                            deepdive-"do" data/model/weights
+                        fi
+                        # dump non-zero weights
                         show_progress output_from "$dest" -- \
-                        deepdive sql eval "
-                            SELECT id
-                                 , isfixed
-                                 , initvalue
-                                 , description
-                                 , categories
-                              FROM dd_graph_weights
-                             WHERE initvalue <> 0
-                        " format=csv | pbzip2 >"$dest"/dd_graph_weights.csv.bz2
+                        deepdive-sql eval "
+                            SELECT description
+                                 , ARRAY_AGG(weight)
+                                 , ARRAY_AGG(categories::text)
+                              FROM dd_inference_result_weights wo
+                                 , dd_graph_weights            wi
+                             WHERE wo.id = wi.id
+                               AND weight <> 0
+                             GROUP BY description
+                        " format=tsv | pbzip2 >"$dest"/dd_graph_weights.tsv.bz2
                         ;;
                 esac
                 # keep a LAST symlink pointing to the last
